# .travis.yml
# This file should be at the root of your project
language: ruby
cache: bundler
before_install:
  - gem install bundler:2.2.14
before_script:
  - chmod +x ./assets/cibuild.sh
script: ./assets/cibuild.sh
  # - bundle exec jekyll algolia
  # bundle exec jekyll build
exclude: [vendor]
sudo: false
branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - main
rvm:
 - 2.7
